### ISSUE TITLE
Hiding the group picture by default when creating a new group

### ISSUE THREAD

**Issue by RahelPhasen** [academic-moodle-cooperation/moodle-mod_grouptool#22]
Hi,

we got a user request wishing to set an default option to hide the group picture when creating a group or making it possible to choose whether to hide the picture or not. 
At the moment everyone sees how often somebody is changing the group because you're just renaming the groups instead of deleting them.

**Comment by goggo24** [comment]
You are right, you can only hide the picture at the moment after you created the group with grouptool via participants lists (Users ->Groups). It could be a new setting - analogous to group messaging we implemented within the grouptool some time ago. 
If you provide a PR we are happy to include it, otherwise i put it in our backlog.

**Comment by t-schroeder** [comment]
Hi @goggo24 ,

I just noticed the "Hide group picture" setting for groups gets removed with 3.11 anyway. So we no longer need this feature. I would therefore close this issue again.
